### ISSUE TITLE
notebook examples

### ISSUE THREAD

**Issue by sistar2020** [BioinfoMachineLearning/GCDM-SBDD#2]
Could you please provide some jupyter notebooks for tutorial purposes?
Thanks.

**Comment by amorehead** [comment]
Hello.

Yes, I will add a notebook or two to show users how to use this codebase (e.g., to generate new 3D molecules for specific protein targets). In fact, the timing of this works out well, since this week I've verified the pipeline's functionality end-to-end for some particular design targets.

Stay tuned!

**Comment by amorehead** [comment]
Hi, @sistar2020. Thanks again for suggesting adding a tutorial notebook series. As requested, you can now find [new Jupyter notebooks](https://github.com/BioinfoMachineLearning/GCDM-SBDD?tab=readme-ov-file#tutorials) guiding users on how to best use `GCDM-SBDD` for designing new 3D molecules for target protein pockets of interest. Let me know if you have any other questions.
